name: barcode_checker
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^9.3.0+1
  barcode: ^2.2.8
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  duration: ^4.0.3
  flash: ^3.1.1
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_form_builder: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage_x: ^10.2.2
  flutter_svg: ^2.0.17
  flutter_thermal_printer: ^1.0.1
  form_builder_validators: ^11.1.1
  hive_ce_flutter: ^2.2.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  multiple_result: ^5.1.0
  path_provider: ^2.1.5
  platform_info: ^5.0.0
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  talker_dio_logger: ^4.6.5
  talker_flutter: ^4.6.5
  talker_riverpod_logger: ^4.6.5
  velocity_x:
    git: https://github.com/Shreemanarjun/VelocityX.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.3
  riverpod_test: ^0.1.6
  slang_build_runner: ^4.4.0
  spot: ^0.17.0
  very_good_analysis: ^7.0.0





flutter:
  uses-material-design: true